#!/usr/bin/env node
/**
 * Photographs → committed responsive derivatives. Run when the photos change;
 * the output is committed, exactly like the Devanagari outlines.
 *
 *     npm run images
 *
 * WHY THIS EXISTS
 * ───────────────
 * The site is a static export, so there is no `next/image` server on the other
 * end of a request — `images: { unoptimized: true }` in next.config.mjs is not a
 * preference, it is the only option available. Ship the originals and the phone
 * downloads a 4MB JPEG to draw it 390px wide.
 *
 * This is the single decision that makes the celebration fast or slow. Nothing
 * else in the second half comes close: a wedding invitation that takes eight
 * seconds on 4G has failed, whatever it looks like when it finally arrives.
 *
 *     assets/photos/<anything>.jpg          originals, never committed
 *          │  sharp → AVIF and WebP, at four widths, never upscaled
 *          ▼
 *     public/img/<slug>-<w>.{avif,webp}     committed derivatives
 *     content/photos.generated.json         dimensions, widths, and a LQIP
 *
 * Committing the output rather than building it in CI is the same call the
 * Devanagari pipeline makes, for the same reason: what is deployed is then
 * exactly what was seen locally, and the deploy needs no native dependency.
 *
 * The manifest carries each photo's real pixel dimensions so that every <img>
 * can declare width and height and reserve its own space. Without that the
 * whole celebration reflows as each photo lands, which is both the worst thing
 * you can do to someone reading on a phone and, measurably, the worst thing you
 * can do to a Lighthouse score.
 *
 * The LQIP is a 20px-wide WebP inlined as a data URI. It is not a placeholder
 * for taste's sake: it means a panel is never a blank rectangle, so a slow
 * connection sees the *shape and colour* of the photograph immediately.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

const SRC_DIR = path.join(root, 'assets/photos')
const OUT_DIR = path.join(root, 'public/img')
const MANIFEST = path.join(root, 'content/photos.generated.json')

/**
 * Four widths, and the largest is 1440 rather than the source.
 *
 * This is read on a phone in portrait. 1440 covers a 3× 480pt screen and a
 * desktop half-width column; anything above it is bytes nobody's eye can use.
 */
const WIDTHS = [480, 768, 1080, 1440]

const SOURCE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.tif', '.tiff', '.avif'])

// AVIF first because it is roughly half of WebP at the same quality, and WebP
// only as the fallback — Safari has had AVIF since 16, so the fallback is for
// the phones in a family group chat that are older than the marriage.
const AVIF = { quality: 52, effort: 4 }
const WEBP = { quality: 76, effort: 5 }

const slugify = (file) =>
  path
    .basename(file, path.extname(file))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

const kb = (n) => `${(n / 1024).toFixed(0)}KB`

/** The widths worth emitting for a source this size. Never upscales. */
function widthsFor(sourceWidth) {
  const fit = WIDTHS.filter((w) => w <= sourceWidth)
  // a source smaller than the smallest step still gets exactly one derivative,
  // at its own size, so every photo has a complete srcset rather than none
  return fit.length ? fit : [sourceWidth]
}

async function main() {
  if (!fs.existsSync(SRC_DIR)) {
    fs.mkdirSync(SRC_DIR, { recursive: true })
  }
  fs.mkdirSync(OUT_DIR, { recursive: true })
  fs.mkdirSync(path.dirname(MANIFEST), { recursive: true })

  const sources = fs
    .readdirSync(SRC_DIR)
    .filter((f) => SOURCE_EXT.has(path.extname(f).toLowerCase()))
    .sort()

  // Anything left behind that is not a readable image and not this folder's own
  // notes. HEIC straight off an iPhone lands here, which is worth saying out
  // loud rather than silently producing a site with no photographs on it.
  const IGNORE = new Set(['.md', '.txt', '.json'])
  const skipped = fs
    .readdirSync(SRC_DIR)
    .filter((f) => !f.startsWith('.'))
    .filter((f) => !SOURCE_EXT.has(path.extname(f).toLowerCase()))
    .filter((f) => !IGNORE.has(path.extname(f).toLowerCase()))
    .filter((f) => fs.statSync(path.join(SRC_DIR, f)).isFile())

  const previous = fs.existsSync(MANIFEST) ? JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) : {}

  const manifest = {
    _readme: [
      'Generated by scripts/build-images.mjs — do not edit.',
      'Drop originals in assets/photos/ and run `npm run images`.',
      'Sizes are the *source* pixel dimensions; `widths` are the derivatives in public/img/.',
    ],
  }

  const seen = new Set()
  let written = 0
  let reused = 0
  let bytes = 0

  for (const file of sources) {
    const slug = slugify(file)
    if (!slug) {
      console.warn(`  ! ${file} — filename has no usable characters, skipped`)
      continue
    }
    if (seen.has(slug)) {
      console.warn(`  ! ${file} — collides with another photo on the slug "${slug}", skipped`)
      continue
    }
    seen.add(slug)

    const src = path.join(SRC_DIR, file)
    const stat = fs.statSync(src)
    // .rotate() with no argument applies the EXIF orientation and drops the tag,
    // so a photo shot in portrait stays in portrait instead of arriving on its
    // side in every browser that ignores the tag on a resized image.
    const input = sharp(src).rotate()
    const meta = await input.metadata()
    if (!meta.width || !meta.height) {
      console.warn(`  ! ${file} — sharp could not read its dimensions, skipped`)
      continue
    }
    // metadata() reports the stored dimensions; after .rotate() the visual ones
    // are swapped for the sideways orientations
    const swap = (meta.orientation ?? 1) >= 5
    const width = swap ? meta.height : meta.width
    const height = swap ? meta.width : meta.height

    const widths = widthsFor(width)
    const stamp = Math.round(stat.mtimeMs)

    const outputs = widths.flatMap((w) => [
      path.join(OUT_DIR, `${slug}-${w}.avif`),
      path.join(OUT_DIR, `${slug}-${w}.webp`),
    ])

    const prior = previous[slug]
    const fresh =
      prior &&
      prior.mtime === stamp &&
      prior.w === width &&
      String(prior.widths) === String(widths) &&
      prior.lqip &&
      outputs.every((p) => fs.existsSync(p))

    if (fresh) {
      manifest[slug] = prior
      reused++
      for (const p of outputs) bytes += fs.statSync(p).size
      continue
    }

    process.stdout.write(`  ${slug}  ${width}×${height}  →`)

    for (const w of widths) {
      const resized = () => sharp(src).rotate().resize({ width: w, withoutEnlargement: true })
      const avif = path.join(OUT_DIR, `${slug}-${w}.avif`)
      const webp = path.join(OUT_DIR, `${slug}-${w}.webp`)
      await resized().avif(AVIF).toFile(avif)
      await resized().webp(WEBP).toFile(webp)
      bytes += fs.statSync(avif).size + fs.statSync(webp).size
      process.stdout.write(` ${w}`)
    }

    const lqipBuf = await sharp(src)
      .rotate()
      .resize({ width: 20 })
      .blur(1.1)
      .webp({ quality: 28, alphaQuality: 40 })
      .toBuffer()

    manifest[slug] = {
      src: file,
      mtime: stamp,
      w: width,
      h: height,
      widths,
      lqip: `data:image/webp;base64,${lqipBuf.toString('base64')}`,
    }
    written++
    process.stdout.write(`  (lqip ${lqipBuf.length}B)\n`)
  }

  /* ── prune ────────────────────────────────────────────────────────────────
   * Derivatives of a photo that has since been deleted or renamed would be
   * committed forever and served to nobody. Only files matching this script's
   * own naming are touched.
   * ---------------------------------------------------------------------- */
  let pruned = 0
  for (const f of fs.readdirSync(OUT_DIR)) {
    const m = /^(.+)-(\d+)\.(avif|webp)$/.exec(f)
    if (!m) continue
    if (seen.has(m[1])) continue
    fs.unlinkSync(path.join(OUT_DIR, f))
    pruned++
  }

  fs.writeFileSync(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`)

  console.log('')
  if (!sources.length) {
    console.log('  No photographs in assets/photos/ yet.')
    console.log('  Every panel will render its ornament instead, which is a')
    console.log('  deliberate state rather than a hole — see components/utsav/Photo.tsx.')
  } else {
    console.log(
      `  ${written} built, ${reused} unchanged, ${pruned} pruned — ${kb(bytes)} in public/img/`,
    )
  }
  if (skipped.length) {
    console.log('')
    console.log(`  Not an image sharp can read, left alone: ${skipped.join(', ')}`)
    console.log('  (HEIC from an iPhone is the usual one — export as JPEG first.)')
  }
  console.log(`  Manifest → ${path.relative(root, MANIFEST)}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
